from .tenants import router as tenants
from .appointments import router as appointments
from .services import router as services
from .auth import router as auth
from .users import router as users
from .clients import router as clients
from .tags import router as tags
from .dashboard import router as dashboard
from .templates import router as templates
from  .communications import router as communications
from .staff import router as staff
from .availability import router as availability
