"""Add price column to services table

Revision ID: 195655731c14
Revises: 9468563a724d
Create Date: 2025-04-26 23:09:05.993880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195655731c14'
down_revision: Union[str, None] = '9468563a724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('appointments_service_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'service_id')
    op.add_column(
    'services',
    sa.Column(
        'price',
        sa.Numeric(precision=10, scale=2),
        nullable=False,
        server_default=sa.text('0.00') # <-- ADD THIS
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'price')
    op.add_column('appointments', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_service_id_fkey', 'appointments', 'services', ['service_id'], ['id'])
    op.alter_column('appointments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
