"""enhance tenant model by adding new fields

Revision ID: 19ba8ab4bfcc
Revises: e2c7423cc7b0
Create Date: 2025-05-03 03:42:58.782547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19ba8ab4bfcc'
down_revision: Union[str, None] = 'e2c7423cc7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address_postal_code', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('tenants', sa.Column('default_currency', sa.String(length=3), server_default='MAD', nullable=False))
    op.add_column('tenants', sa.Column('cancellation_policy_text', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('business_hours_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('booking_widget_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('tenants_subdomain_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.create_unique_constraint('tenants_subdomain_key', 'tenants', ['subdomain'])
    op.drop_column('tenants', 'booking_widget_config')
    op.drop_column('tenants', 'business_hours_config')
    op.drop_column('tenants', 'cancellation_policy_text')
    op.drop_column('tenants', 'default_currency')
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'address_country')
    op.drop_column('tenants', 'address_postal_code')
    op.drop_column('tenants', 'address_state')
    op.drop_column('tenants', 'address_city')
    op.drop_column('tenants', 'address_street')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'website_url')
    # ### end Alembic commands ###
