"""Update SQLAlchemy model for native appointmentstatus enum

Revision ID: 87f9b5ffbe21
Revises: 89c19cb62a8f
Create Date: 2025-04-24 21:17:12.601220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f9b5ffbe21'
down_revision: Union[str, None] = '89c19cb62a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'done', name='appointmentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'cancelled', 'done', name='appointmentstatus'),
               nullable=True)
    # ### end Alembic commands ###
