"""add_end_datetime_utc_to_appointments

Revision ID: af1907a49e0d
Revises: 9f1f2b1cf134
Create Date: 2025-05-25 02:27:25.841912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime


# revision identifiers, used by Alembic.
revision: str = 'af1907a49e0d'
down_revision: Union[str, None] = '9f1f2b1cf134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_datetime_utc', DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_appointments_end_datetime_utc'), 'appointments', ['end_datetime_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_end_datetime_utc'), table_name='appointments')
    op.drop_column('appointments', 'end_datetime_utc')
    # ### end Alembic commands ###
