"""Add reminder_interval_hours to tenant

Revision ID: be67024b60d5
Revises: 0225bad5f296
Create Date: 2025-05-04 19:39:07.470767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67024b60d5'
down_revision: Union[str, None] = '0225bad5f296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('reminder_interval_hours', sa.Integer(), server_default='24', nullable=True, comment='Hours before appointment to send reminder (null=disabled)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'reminder_interval_hours')
    # ### end Alembic commands ###
