"""make appointments time indexed

Revision ID: c4441d8b33ff
Revises: 712ff85625dc
Create Date: 2025-04-28 02:56:19.382718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4441d8b33ff'
down_revision: Union[str, None] = '712ff85625dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_appointment_time'), 'appointments', ['appointment_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_appointment_time'), table_name='appointments')
    # ### end Alembic commands ###
