"""Update comm log direction enum and column

Revision ID: f88aec883d1f
Revises: be67024b60d5
Create Date: 2025-05-07 16:05:10.032645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f88aec883d1f'
down_revision: Union[str, None] = 'be67024b60d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications_log', sa.Column('direction', postgresql.ENUM('OUTBOUND', 'INBOUND', 'SYSTEM', name='communicationdirection', create_type=True), server_default='SYSTEM', nullable=False))

    op.add_column('communications_log', sa.Column('notes', sa.Text(), nullable=True, comment='Main content/notes of the communication'))
    


    # Add indexes
    op.create_index('ix_comm_log_tenant_direction', 'communications_log', ['tenant_id', 'direction'], unique=False)
    op.create_index(op.f('ix_communications_log_direction'), 'communications_log', ['direction'], unique=False)
    op.drop_column('communications_log', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications_log', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_communications_log_direction'), table_name='communications_log')
    op.drop_index('ix_comm_log_tenant_direction', table_name='communications_log')
    op.drop_column('communications_log', 'notes')
    op.drop_column('communications_log', 'direction')
    # ### end Alembic commands ###
